services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports: 
      - "3000:80"
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_LEARNHOUSE_MULTI_ORG: ${NEXT_PUBLIC_LEARNHOUSE_MULTI_ORG}
      NEXT_PUBLIC_LEARNHOUSE_DEFAULT_ORG: ${NEXT_PUBLIC_LEARNHOUSE_DEFAULT_ORG}
      NEXT_PUBLIC_LEARNHOUSE_TOP_DOMAIN: ${NEXT_PUBLIC_LEARNHOUSE_TOP_DOMAIN}
      NEXT_PUBLIC_LEARNHOUSE_BACKEND_URL: ${NEXT_PUBLIC_LEARNHOUSE_BACKEND_URL}
      NEXT_PUBLIC_LEARNHOUSE_DOMAIN: ${NEXT_PUBLIC_LEARNHOUSE_DOMAIN}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      LEARNHOUSE_COOKIE_DOMAIN: ${LEARNHOUSE_COOKIE_DOMAIN}
      LEARNHOUSE_SQL_CONNECTION_STRING: ${LEARNHOUSE_SQL_CONNECTION_STRING}
      LEARNHOUSE_REDIS_CONNECTION_STRING: ${LEARNHOUSE_REDIS_CONNECTION_STRING}
      LEARNHOUSE_CHROMADB_HOST: ${LEARNHOUSE_CHROMADB_HOST}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=learnhouse
      - POSTGRES_PASSWORD=learnhouse
      - POSTGRES_DB=learnhouse
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U learnhouse"]
      interval: 5s
      timeout: 4s
      retries: 5
  redis:
    image: redis:7.2.3
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 4s
      retries: 5
  chromadb:
    image: chromadb/chroma:0.5.16
    ports:
      - "8000:8000"
